//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Java.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJavaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public partial class JavaBaseListener : IJavaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.class_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClass_definition([NotNull] JavaParser.Class_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.class_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClass_definition([NotNull] JavaParser.Class_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] JavaParser.MethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] JavaParser.MethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] JavaParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] JavaParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] JavaParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] JavaParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.method_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_call([NotNull] JavaParser.Method_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.method_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_call([NotNull] JavaParser.Method_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.if_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_op([NotNull] JavaParser.If_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.if_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_op([NotNull] JavaParser.If_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.var_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_definition([NotNull] JavaParser.Var_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.var_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_definition([NotNull] JavaParser.Var_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] JavaParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] JavaParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] JavaParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] JavaParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.array_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_access([NotNull] JavaParser.Array_accessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.array_access"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_access([NotNull] JavaParser.Array_accessContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
