//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Java.g4 by ANTLR 4.7.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JavaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.1")]
[System.CLSCompliant(false)]
public interface IJavaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_definition([NotNull] JavaParser.Class_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.class_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_definition([NotNull] JavaParser.Class_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod([NotNull] JavaParser.MethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod([NotNull] JavaParser.MethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] JavaParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] JavaParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JavaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JavaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod_call([NotNull] JavaParser.Method_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.method_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod_call([NotNull] JavaParser.Method_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.if_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_op([NotNull] JavaParser.If_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.if_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_op([NotNull] JavaParser.If_opContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.var_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_definition([NotNull] JavaParser.Var_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.var_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_definition([NotNull] JavaParser.Var_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] JavaParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] JavaParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] JavaParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] JavaParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JavaParser.array_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_access([NotNull] JavaParser.Array_accessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JavaParser.array_access"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_access([NotNull] JavaParser.Array_accessContext context);
}
